// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NormalCardKind } from "./NormalCardKind";
import type { SpecialCardKind } from "./SpecialCardKind";

export type CardKind = { "tag": "Normal", "fields": NormalCardKind } | { "tag": "Special", "fields": SpecialCardKind };