// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardKind } from "./CardKind";
import type { Color } from "./Color";

export type Card = { color: Color, kind: CardKind, id: number, };