// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { UserData } from "./UserData";

export interface GameState { users: Array<UserData>, ownCards: Array<Card>, turnIndex: number, topCard: Card | null, selfIndex: number, }