// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { UserData } from "./UserData";

export interface GameState { users: Array, own_cards: Array, turn_index: number, top_card: Card | null, self_index: number, }