// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LobbyData { name: string, players: number, max_players: number, id: string, }