// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

export type Request = { "tag": "PlayCard", "fields": [number, Color] } | { "tag": "TakeCard" } | { "tag": "SendMessage", "fields": { content: string, } };