// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

export type Request = { "tag": "PlaySpecialCard", "fields": [number, Color] } | { "tag": "PlayCards", "fields": Array<number> } | { "tag": "TakeCard" } | { "tag": "SendMessage", "fields": { content: string, } };