// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";
import type { GameState } from "./GameState";

export type Response = { "tag": "ChatMessage", "fields": ChatMessage } | { "tag": "GameState", "fields": GameState };