// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Avatar } from "./Avatar";

export type UserCreate = { name: string, avatar: Avatar, };